services:
  backend:
    image: AlvinCao88/quirknotes_backend:latest
    context: .
      dockerfile: Dockerfile_backend
      target: backend
    ports:
    - "4000:4000"
    environment:
    - ENV=Docker
    depends_on:
    - mongodb
    mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"version: '3'

services:
  backend:
    image: AlvinCao88/quirknotes_backend:latest
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  frontend:
    image: AlvinCao88/quirknotes_frontend:latest
    ports:
      - "3000:80"

    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    image: AlvinCao88/quirknotes_frontend:latest
    ports:
      - "3000:80"